name: cabal
description: "Flutter's biggest open secret."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-120.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_gpu:
    path: ../engine/src/flutter/lib/gpu
  vector_math: ^2.1.4
  ffi:
  oxygen: ^0.2.0
  flutter_fancy_tree_view:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  ffigen:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - gen/cabal.shaderbundle
