name: cabal
description: "Flutter's biggest open secret."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-120.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_gpu:
    path: ../../engine/src/flutter/lib/gpu
  flutter_bullet:
    path: deps/flutter_bullet
  vector_math: ^2.1.4
  image: ^4.1.3
  flat_buffers: ^23.5.26

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - gen/cabal.shaderbundle
    - assets/flutter_logo.model
    - assets/flutter_logo_BaseColor_rgba.png
    - assets/flutter_logo_Normal_rgba.png
    - assets/flutter_logo_OcclusionRoughnessMetallic_rgba.png
